name: iOS Build

on:
  push:
    branches: [ main2 ]
  pull_request:
    branches: [ main2 ]

jobs:
  build:
    runs-on: macos-14

    defaults:
      run:
        working-directory: iOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby (for CocoaPods if needed)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install CocoaPods dependencies (可选)
        run: |
          if [ -f "Podfile" ]; then
            gem install cocoapods
            pod install
          fi

      - name: test
        run: |
          # cat /etc/ssh/sshd_config
          whoami
          sudo systemsetup -getremotelogin

          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate \
            -configure \
            -access -on \
            -users runner \
            -privs -all \
            -restart -agent -menu

          sudo defaults write /Library/Preferences/com.apple.VNCSettings.plist Password -data $(echo -n 'your_password' | iconv -t UTF-16LE | openssl md5 -binary | xxd -p)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent


